'use strict';

const { createHash } = require('node:crypto');
const {
  PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS,
  PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS_CREATE_SQL,
  PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS_RUNTIME_GUARDS_SQL,
  PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS_OWNED_OBJECTS,
} = require('./projectDatabaseMigration31LegacyGaps');
const {
  PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGERS,
  PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGER_CREATE_STATE_SQL,
  PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGER_RUNTIME_GUARDS_SQL,
  PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGER_OWNED_OBJECTS,
} = require('./projectDatabaseMigration31DurableLedgers');

const VERSION = 31;
const FROM_VERSION = 30;
const NAME = 'strict-durable-evidence-boundaries';
const DOWN_POLICY = 'backup-only';
const CHECKSUM_CANONICALIZATION = 't8-project-database-migration-v2';

// Generated by applying the composed schema-31 DDL to all ten accepted
// schema-30 lineage fixtures. Every lineage produced this exact extension.
const EXTENSION_FINGERPRINT = '2ac8af2dfa9ec92cdf1f2a978dc9a924ad147efbb8ad2fa749df6b522628e658';

const componentChecksums = Object.freeze({
  legacySnapshotGaps: PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS.checksum,
  durableLedgers: PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGERS.checksum,
});

const UP_SQL = String.raw`
${PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS_CREATE_SQL}
${PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGER_CREATE_STATE_SQL}
${PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGER_RUNTIME_GUARDS_SQL}
${PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS_RUNTIME_GUARDS_SQL}
`;

// Schema 31 records compatibility exceptions and exact capacity accounting.
// Neither can be inverted honestly after the database has accepted writes;
// downgrade always restores the verified schema-30 recovery point.
const DOWN_SQL = '';

const ownedObjects = Object.freeze({
  tables: Object.freeze([
    ...PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS_OWNED_OBJECTS.tables,
    ...PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGER_OWNED_OBJECTS.tables,
  ]),
  indexes: Object.freeze([
    ...PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS_OWNED_OBJECTS.indexes,
    ...PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGER_OWNED_OBJECTS.indexes,
  ]),
  views: Object.freeze([
    ...PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS_OWNED_OBJECTS.views,
    ...PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGER_OWNED_OBJECTS.views,
  ]),
  triggers: Object.freeze([
    ...PROJECT_DATABASE_MIGRATION_31_LEGACY_GAPS_OWNED_OBJECTS.triggers,
    ...PROJECT_DATABASE_MIGRATION_31_DURABLE_LEDGER_OWNED_OBJECTS.triggers,
  ]),
});

for (const kind of Object.keys(ownedObjects)) {
  const values = ownedObjects[kind];
  if (new Set(values).size !== values.length) {
    throw new Error(`schema31 composed ${kind} object names collide`);
  }
}

const ownedObjectNames = Object.freeze([
  ...ownedObjects.tables,
  ...ownedObjects.indexes,
  ...ownedObjects.views,
  ...ownedObjects.triggers,
]);

const imperativeContract = Object.freeze({
  format: 't8-project-database-migration-31-imperative-v1',
  components: componentChecksums,
  extensionFingerprint: EXTENSION_FINGERPRINT,
  phases: Object.freeze([
    Object.freeze({
      id: 'locked-schema30-gate',
      algorithmVersion: 'fingerprint-data-version-backup-v1',
      invariants: Object.freeze([
        'acquire-immediate-before-classification-or-ddl',
        'verified-schema30-backup-data-version-must-match-under-lock',
        'schema29-and-schema30-fingerprints-and-receipts-remain-exact',
      ]),
    }),
    Object.freeze({
      id: 'create-composed-schema31-extension',
      algorithmVersion: 'legacy-gap-plus-durable-state-v1',
      invariants: Object.freeze([
        'legacy-gap-table-exists-before-classification-without-runtime-insert-guard',
        'durable-policy-usage-and-run-event-binding-tables-exist-before-backfill',
        'schema28-through-schema30-base-objects-are-not-rewritten',
      ]),
    }),
    Object.freeze({
      id: 'initialize-durable-ledger-accounting',
      algorithmVersion: 'four-kind-project-database-accounting-v1',
      invariants: Object.freeze([
        'every-existing-project-and-the-database-singleton-have-exact-policy-and-usage',
        'run-events-have-one-derived-project-binding-with-frozen-logical-bytes',
        'preexisting-overage-is-preserved-without-deleting-or-truncating-evidence',
      ]),
    }),
    Object.freeze({
      id: 'repair-or-classify-owner-snapshot-gaps',
      algorithmVersion: 'current-head-repair-terminalize-exact-gap-v1',
      invariants: Object.freeze([
        'current-head-snapshots-are-repaired-only-from-the-byte-equivalent-canvas-document',
        'unsafe-active-intents-and-runs-are-terminalized-before-the-gap-set-is-frozen',
        'unrecoverable-history-receives-one-owner-scoped-immutable-compatibility-record',
      ]),
    }),
    Object.freeze({
      id: 'install-schema31-runtime-guards',
      algorithmVersion: 'capacity-owner-identity-fail-close-v1',
      invariants: Object.freeze([
        'durable-row-project-and-database-gates-backstop-every-direct-insert',
        'legacy-gap-insert-update-delete-and-owner-id-reuse-are-denied',
        'run-event-and-output-commit-accounting-release-only-with-authoritative-cascade',
      ]),
    }),
    Object.freeze({
      id: 'verify-composed-schema31-state',
      algorithmVersion: 'owner-partition-accounting-fk-quick-v1',
      invariants: Object.freeze([
        'every-managed-owner-has-one-exact-pin-or-one-exact-legacy-gap-never-both',
        'project-and-database-usage-exactly-match-all-four-durable-ledgers',
        'foreign-key-check-is-empty-and-quick-check-is-ok',
      ]),
    }),
    Object.freeze({
      id: 'lineage-receipt-commit',
      algorithmVersion: 'schema30-base-plus-schema31-extension-v1',
      invariants: Object.freeze([
        'schema31-owned-extension-fingerprint-is-frozen',
        'every-accepted-schema30-lineage-has-one-explicit-schema31-target-fingerprint',
        'ledger-and-checksummed-receipt-commit-in-the-same-immediate-transaction',
      ]),
    }),
  ]),
});

function normalizeSql(sql) {
  return String(sql).replace(/\r\n?/g, '\n').trim();
}

const canonicalChecksumInput = JSON.stringify({
  format: CHECKSUM_CANONICALIZATION,
  version: VERSION,
  fromVersion: FROM_VERSION,
  name: NAME,
  downPolicy: DOWN_POLICY,
  UP_SQL: normalizeSql(UP_SQL),
  DOWN_SQL: normalizeSql(DOWN_SQL),
  ownedObjectNames,
  imperativeContract,
});

const checksum = createHash('sha256')
  .update(canonicalChecksumInput, 'utf8')
  .digest('hex');

const definition = Object.freeze({
  version: VERSION,
  fromVersion: FROM_VERSION,
  name: NAME,
  downPolicy: DOWN_POLICY,
  checksumAlgorithm: 'sha256',
  checksumCanonicalization: CHECKSUM_CANONICALIZATION,
  checksum,
  UP_SQL,
  DOWN_SQL,
  ownedObjects,
  ownedObjectNames,
  imperativeContract,
});

module.exports = Object.freeze({
  PROJECT_DATABASE_MIGRATION_31: definition,
  PROJECT_DATABASE_MIGRATION_31_UP_SQL: UP_SQL,
  PROJECT_DATABASE_MIGRATION_31_DOWN_SQL: DOWN_SQL,
  PROJECT_DATABASE_MIGRATION_31_IMPERATIVE_CONTRACT: imperativeContract,
  PROJECT_DATABASE_SCHEMA_31_OWNED_OBJECTS: ownedObjects,
  PROJECT_DATABASE_SCHEMA_31_OWNED_OBJECT_NAMES: ownedObjectNames,
  PROJECT_DATABASE_SCHEMA_31_EXTENSION_FINGERPRINT: EXTENSION_FINGERPRINT,
  PROJECT_DATABASE_MIGRATION_31_COMPONENT_CHECKSUMS: componentChecksums,
});
